name: PHP type checking and unit testing

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        php-versions: ["7.4", "8.0", "8.1", "8.2"]
        symfony-versions: ["~3.0", "~4.0", "~5.0", "~6.0"]
        exclude:
          - php-versions: "7.4"
            symfony-versions: "~6.0"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, json
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Declare required Symfony version
      run: |
        composer require --no-update symfony/dependency-injection ${{ matrix.symfony-versions }}
        composer require --no-update symfony/config ${{ matrix.symfony-versions }}
        composer require --no-update symfony/yaml ${{ matrix.symfony-versions }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run type checker
      run: ./vendor/bin/psalm --php-version=${{ matrix.php-versions}}

    - name: Run unit tests
      run: ./vendor/bin/phpunit --testdox
